# Directory for inputs and outputs
workdir: "/home/sutripa/rnaseq_pipeline"


# Raw samples (prefix before R1/R2)
samples:
  - "6_A_"
  - "Ct_A_"

# Reference genome and annotation
reference: "/home/sutripa/rnaseq_pipeline/MLA_UU774new1.fna"
annotation: "/home/sutripa/rnaseq_pipeline/genomic.gff"

# Adapter file
adapters: "/home/sutripa/Tools/adapters.fasta.gz"

output:
  counts: "read_count"

featurecounts:
  feature_type: "CDS"     # corresponds to -t
  attribute: "ID"         # corresponds to -g
  format: "GFF"           # corresponds to -F
  paired: true            # corresponds to -p

